### PR TITLE
Requirement Doc

### PR DESCRIPTION
**Pull request by ssh24**
# Description

This PR includes the Latex generated Requirement Document which has the following outline:
- Context Diagram
- Monitored Variables
- Controlled Variables
- Mode Diagram
- R-description
- E-description
- Abstract Variables
- Function tables for each controlled variables
- PVS validation
- Use cases
- Acceptance Tes
- Appendix

### CODE REVIEW

**Comment by ssh24** [comment]
@johnga1995 Please perform a solid proof read on the whole document to find any mistakes before I can land it to the main branch.

**Review by johnga1995 — COMMENTED** [review]
1 - 5. Control Variables: i think the range of c_md should have "fail" instead of "failed" since we use "fail" in  pvs spec.
2 -  6. Mode Diagram: what is the "guard" condition in the Rationale?
3 - Req 5 on page 13 misspelled Ttemperature. Also i think remove this part "temperature range, m al + 0.5 <= m tm <= m ah − 0.5 " in 3rd column since it doesnt really make sense. 

4 - Page 16 in the rationale for ENV 4, will baby suffer from hypothermia if too hot? I think thats only for too cold. <= 93 F

5- Page 23 Validation: mode_ft there are actually 9 TCCs not 5 according to pvs proof summary

**Comment by ssh24** [comment]
- [x] 1 - Fixed
- [x] 2 - Fixed
- [x] 3 - Fixed. The range is required to make it more clear to the reader.
- [x] 4 - No Change. It is `hyperthermia` not `hypothermia`.
- [x] 5 - Fixed

**Comment by johnga1995** [comment]
Looks good now. I think we can submit.

**Pull request merged**
